# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - RelexInterviewUI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_2f986a45510143c6aba8bd50b64de326 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ba5767ee61b14a63860d44fe90a09ca4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2f986a45510143c6aba8bd50b64de326 }}/relex-interview-ui:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'RelexInterviewUI'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5b8ebc305d4d498ab3d2b008d3e16b44 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2f986a45510143c6aba8bd50b64de326 }}/shahrzadj1993/relex-interview-ui:${{ github.sha }}'
